/**
 * Tren inferior, segunda tanda: las variantes.
 *
 * Lo de `inferior.ts` es el esqueleto —lo que entra en casi todos los planes—.
 * Esto son las variantes que hacen falta para que un bloque de ocho semanas no
 * sea el mismo día repetido: otra máquina, otra pierna, otro ángulo.
 */

import type { Ejercicio } from "../ejercicios";

export const INFERIOR_2: Ejercicio[] = [
  {
    id: "hack-squat",
    nombre: "Hack squat",
    alias: ["hack", "sentadilla hack", "máquina hack"],
    grupo: "cuadriceps",
    secundarios: ["gluteo"],
    material: "maquina",
    patron: "rodilla",
    nivel: "media",
    pasos: [
      "Espalda y cadera pegadas al respaldo, hombros bajo las almohadillas.",
      "Pies a la anchura de la cadera en el centro de la plataforma.",
      "Baja controlando hasta la rodilla en ángulo recto o algo más.",
      "Empuja con todo el pie sin bloquear la rodilla arriba.",
    ],
    ajuste: [
      "Seguros a un palmo por debajo de tu punto más bajo.",
      "Pies más altos reparte a glúteo; más bajos, todo a cuádriceps.",
      "Espalda pegada al respaldo todo el recorrido.",
    ],
    errores: [
      "Despegar la cadera abajo.",
      "Dejar que las rodillas se metan hacia dentro al subir.",
    ],
    senales: "Cuádriceps a tope con la espalda protegida: es la sentadilla para ir pesada sin técnica de barra.",
    cuidado: "Con molestia de rodilla, acorta el recorrido antes que quitar peso.",
    sustitutos: [
      { id: "prensa-45", motivo: "ocupada" },
      { id: "sentadilla-multipower", motivo: "sin-maquina" },
    ],
    imagen: null,
    video: null,
  },
  {
    id: "prensa-horizontal",
    nombre: "Prensa horizontal",
    alias: ["prensa sentada", "prensa horizontal"],
    grupo: "cuadriceps",
    secundarios: ["gluteo"],
    material: "maquina",
    patron: "rodilla",
    nivel: "inicia",
    pasos: [
      "Siéntate con la espalda bien apoyada y los pies en la plataforma.",
      "Ajusta el asiento para que la rodilla quede algo más cerrada que 90º al empezar.",
      "Empuja con todo el pie hasta casi estirar.",
      "Vuelve controlando sin que la cadera se enrolle.",
    ],
    ajuste: [
      "Asiento: la rodilla algo más cerrada que el ángulo recto al empezar.",
      "Respaldo recto y espalda pegada.",
    ],
    errores: [
      "Empujar con la punta del pie.",
      "Bloquear la rodilla de golpe.",
    ],
    senales: "Es la más fácil de entrar y salir y la que mejor va con poca movilidad de cadera.",
    cuidado: null,
    sustitutos: [
      { id: "prensa-45", motivo: "ocupada" },
      { id: "sentadilla-goblet", motivo: "sin-maquina" },
    ],
    imagen: null,
    video: null,
  },
  {
    id: "prensa-una-pierna",
    nombre: "Prensa a una pierna",
    alias: ["prensa unilateral", "prensa una pierna"],
    grupo: "gluteo",
    secundarios: ["cuadriceps", "femoral"],
    material: "maquina",
    patron: "rodilla",
    nivel: "media",
    pasos: [
      "Un solo pie en el centro-alto de la plataforma.",
      "La otra pierna fuera, apoyada y relajada.",
      "Baja hasta donde la cadera no se despegue.",
      "Empuja con el talón y repite antes de cambiar.",
    ],
    ajuste: [
      "Pie centrado: si lo pones al borde, la rodilla se va hacia dentro.",
      "Menos peso del que crees: una pierna no es la mitad de dos.",
    ],
    errores: [
      "Girar la cadera para empujar más.",
      "Dejar la pierna libre colgando y arquear la espalda.",
    ],
    senales: "Enseña qué lado tira menos, que es justo lo que hay que igualar.",
    cuidado: null,
    sustitutos: [
      { id: "bulgara", motivo: "ocupada" },
      { id: "step-up-cajon", motivo: "casa" },
    ],
    imagen: null,
    video: null,
  },
  {
    id: "sentadilla-sumo-mancuerna",
    nombre: "Sentadilla sumo con mancuerna",
    alias: ["sumo", "sentadilla sumo", "sentadilla abierta"],
    grupo: "gluteo",
    secundarios: ["cuadriceps"],
    material: "mancuerna",
    patron: "rodilla",
    nivel: "inicia",
    pasos: [
      "Pies más anchos que los hombros y puntas hacia fuera.",
      "Mancuerna sujeta con las dos manos, colgando entre las piernas.",
      "Baja recta, abriendo las rodillas en la dirección de las puntas.",
      "Sube apretando el glúteo arriba.",
    ],
    ajuste: [],
    errores: [
      "Rodillas hacia dentro.",
      "Inclinar el tronco hacia delante en vez de bajar recta.",
    ],
    senales: "Glúteo y parte interna del muslo. Si notas tirón en la ingle, cierra un poco los pies.",
    cuidado: null,
    sustitutos: [
      { id: "sentadilla-goblet", motivo: "ocupada" },
      { id: "prensa-pies-altos", motivo: "sin-maquina" },
    ],
    imagen: null,
    video: null,
  },
  {
    id: "peso-muerto-convencional",
    nombre: "Peso muerto convencional",
    alias: ["peso muerto", "deadlift"],
    grupo: "espalda",
    secundarios: ["femoral", "gluteo"],
    material: "barra",
    patron: "bisagra",
    nivel: "avanzada",
    pasos: [
      "Barra pegada a la espinilla, pies a la anchura de la cadera.",
      "Agarra fuera de las piernas, saca pecho y tensa la espalda.",
      "Empuja el suelo con las piernas y acompaña con la cadera.",
      "Arriba, de pie y firme; baja llevando la cadera atrás.",
    ],
    ajuste: [],
    errores: [
      "Tirar con la espalda antes de que se muevan las piernas.",
      "Separar la barra del cuerpo.",
      "Perder la espalda plana al bajar.",
    ],
    senales: "Pierna y espalda juntas. Es técnico: si la espalda se redondea, se para la serie.",
    cuidado: "Fuera del plan con cualquier molestia lumbar; para esos casos está el rumano con mancuernas o el curl femoral.",
    sustitutos: [
      { id: "peso-muerto-rumano", motivo: "mas-facil" },
      { id: "hiperextensiones", motivo: "lumbar" },
    ],
    imagen: null,
    video: null,
  },
  {
    id: "zancada-atras",
    nombre: "Zancada hacia atrás",
    alias: ["zancada inversa", "reverse lunge", "desplante atrás"],
    grupo: "gluteo",
    secundarios: ["cuadriceps", "core"],
    material: "mancuerna",
    patron: "rodilla",
    nivel: "inicia",
    pasos: [
      "De pie, una mancuerna en cada mano.",
      "Da un paso largo hacia atrás y baja la rodilla casi al suelo.",
      "El peso se queda en el talón de la pierna de delante.",
      "Empuja para volver al centro y cambia.",
    ],
    ajuste: [],
    errores: [
      "Paso corto, que lleva todo a la rodilla.",
      "Dejar caer la rodilla de atrás de golpe.",
    ],
    senales: "Más amable con la rodilla que la zancada hacia delante: es la versión por defecto si hay molestia.",
    cuidado: null,
    sustitutos: [
      { id: "zancada-mancuernas", motivo: "mas-dificil" },
      { id: "step-up-cajon", motivo: "rodilla" },
    ],
    imagen: null,
    video: null,
  },
  {
    id: "patada-gluteo-maquina",
    nombre: "Patada de glúteo en máquina",
    alias: ["glute kickback", "extensión de cadera en máquina"],
    grupo: "gluteo",
    secundarios: ["femoral"],
    material: "maquina",
    patron: "aislamiento",
    nivel: "inicia",
    pasos: [
      "Apoya el pecho en el respaldo y el pie en la plataforma.",
      "Empuja la plataforma atrás apretando el glúteo.",
      "Aguanta medio segundo en el punto final.",
      "Vuelve despacio hasta notar el estiramiento.",
    ],
    ajuste: [
      "Altura del apoyo: la cadera justo en el eje de giro.",
      "Agárrate a las asas para que el tronco no se mueva.",
    ],
    errores: [
      "Arquear la espalda para empujar más lejos.",
      "Recorrido corto con mucho peso.",
    ],
    senales: "Glúteo aislado, sin que la espalda participe. Es de las pocas máquinas que lo consigue de verdad.",
    cuidado: null,
    sustitutos: [
      { id: "patada-gluteo-polea", motivo: "ocupada" },
      { id: "patada-gluteo-cuadrupedia", motivo: "casa" },
    ],
    imagen: null,
    video: null,
  },
  {
    id: "abduccion-polea-de-pie",
    nombre: "Abducción de cadera en polea",
    alias: ["abducción en polea", "apertura de pierna en polea"],
    grupo: "gluteo",
    secundarios: ["core"],
    material: "polea",
    patron: "aislamiento",
    nivel: "media",
    pasos: [
      "Tobillera en la pierna de fuera y polea abajo del todo.",
      "De lado a la torre, agarrada con la mano de dentro.",
      "Lleva la pierna hacia fuera sin girar la cadera.",
      "Vuelve despacio sin apoyar del todo.",
    ],
    ajuste: [
      "Polea en el agujero más bajo.",
      "Un paso de separación para que haya tensión desde el principio.",
    ],
    errores: [
      "Inclinar el tronco al lado contrario para llegar más.",
      "Girar la punta del pie hacia arriba.",
    ],
    senales: "Arriba y afuera del glúteo, de pie: es la versión que más se parece a cómo se usa al caminar.",
    cuidado: null,
    sustitutos: [
      { id: "abductores-maquina", motivo: "ocupada" },
      { id: "paseo-lateral-banda", motivo: "casa" },
    ],
    imagen: null,
    video: null,
  },
  {
    id: "curl-femoral-pie",
    nombre: "Curl femoral de pie a una pierna",
    alias: ["femoral de pie", "curl de pierna de pie"],
    grupo: "femoral",
    secundarios: [],
    material: "maquina",
    patron: "aislamiento",
    nivel: "inicia",
    pasos: [
      "De pie, apoyada en el pecho y con un pie en el rodillo.",
      "Dobla la rodilla llevando el talón al glúteo.",
      "Aprieta arriba medio segundo.",
      "Baja despacio sin dejar caer el peso.",
    ],
    ajuste: [
      "Rodillo por encima del talón.",
      "Rodilla alineada con el eje de la máquina.",
    ],
    errores: [
      "Balancear la cadera para ayudarse.",
      "Girar el pie.",
    ],
    senales: "Trabaja una pierna cada vez: va muy bien cuando un lado va por detrás del otro.",
    cuidado: null,
    sustitutos: [
      { id: "curl-femoral-tumbada", motivo: "ocupada" },
      { id: "curl-femoral-sentada", motivo: "ocupada" },
    ],
    imagen: null,
    video: null,
  },
  {
    id: "elevacion-talones-sentada",
    nombre: "Elevación de talones sentada",
    alias: ["gemelo sentada", "sóleo", "gemelos sentada"],
    grupo: "gemelo",
    secundarios: [],
    material: "maquina",
    patron: "aislamiento",
    nivel: "inicia",
    pasos: [
      "Sentada, almohadilla sobre la rodilla y punta de los pies en el apoyo.",
      "Sube los talones todo lo que puedas.",
      "Aguanta arriba un segundo.",
      "Baja despacio hasta el estiramiento.",
    ],
    ajuste: [
      "Almohadilla sobre el muslo, cerca de la rodilla, bien apretada.",
      "Solo la punta del pie apoyada.",
    ],
    errores: ["Rebotar abajo.", "Recorrido corto."],
    senales: "Con la rodilla doblada trabaja el sóleo, que es el que sostiene de pie todo el día. Complementa a los de pie.",
    cuidado: null,
    sustitutos: [
      { id: "gemelos-prensa", motivo: "ocupada" },
      { id: "gemelos-de-pie", motivo: "casa" },
    ],
    imagen: null,
    video: null,
  },
];
