/**
 * Tren inferior: glúteo, cuádriceps, femoral y gemelo.
 *
 * Es el grueso de lo que se planifica aquí, así que es lo primero que se
 * escribió. Cada ficha está redactada para leerse DE PIE y con prisa, delante
 * de la máquina: frases cortas, lo que hay que tocar primero, y la señal que
 * dice si va bien. Nada de teoría; para eso está la llamada.
 */

import type { Ejercicio } from "../ejercicios";

export const INFERIOR: Ejercicio[] = [
  /* ---- Glúteo ---------------------------------------------------------- */
  {
    id: "hip-thrust-maquina",
    nombre: "Hip thrust en máquina",
    alias: ["hip thrust", "empuje de cadera en máquina", "glute drive"],
    grupo: "gluteo",
    secundarios: ["femoral", "cuadriceps"],
    material: "maquina",
    patron: "empuje-cadera",
    nivel: "inicia",
    pasos: [
      "Siéntate con la espalda apoyada en el respaldo y la almohadilla justo encima de la cadera, no sobre la tripa.",
      "Pies a la anchura de la cadera, con el talón debajo de la rodilla cuando subas.",
      "Mete la barbilla, mira al frente y empuja con los talones hasta hacer una línea recta de rodilla a hombro.",
      "Aprieta el glúteo un segundo arriba y baja controlando, sin llegar a soltar el peso abajo.",
    ],
    ajuste: [
      "Respaldo: el borde de arriba, justo debajo del omóplato.",
      "Almohadilla: sobre el pliegue de la cadera.",
      "Cinturón bien apretado; si se mueve al subir, está flojo.",
      "Plataforma: rodilla a 90º cuando estés arriba.",
    ],
    errores: [
      "Arquear la zona lumbar arriba en vez de terminar apretando el glúteo.",
      "Subir de puntillas: el peso va en el talón.",
      "Poner tanto peso que el recorrido se queda a medias.",
    ],
    senales: "Lo notas en el glúteo y no en la lumbar ni en el cuádriceps. Si al día siguiente molesta la espalda baja, bajamos peso y revisamos la almohadilla.",
    cuidado: "Si notas pinzamiento delante de la cadera arriba, acorta el recorrido antes de quitar peso.",
    sustitutos: [
      { id: "hip-thrust-barra", motivo: "ocupada" },
      { id: "hip-thrust-multipower", motivo: "ocupada" },
      { id: "puente-gluteo-suelo", motivo: "casa" },
      { id: "hip-thrust-una-pierna", motivo: "sin-maquina" },
    ],
    imagen: null,
    video: null,
  },
  {
    id: "hip-thrust-barra",
    nombre: "Hip thrust con barra",
    alias: ["empuje de cadera con barra", "hip thrust banco"],
    grupo: "gluteo",
    secundarios: ["femoral"],
    material: "barra",
    patron: "empuje-cadera",
    nivel: "media",
    pasos: [
      "Siéntate en el suelo con la espalda apoyada en el banco, a la altura de la punta del omóplato.",
      "Rueda la barra hasta la cadera y pon una almohadilla gruesa entre la barra y el hueso.",
      "Pies a la anchura de la cadera, talones debajo de la rodilla.",
      "Empuja con los talones hasta la línea recta rodilla-hombro, aprieta arriba y baja controlando.",
    ],
    ajuste: [],
    errores: [
      "El banco demasiado alto o demasiado bajo: tiene que quedar en la punta del omóplato.",
      "Mirar al techo: la barbilla va metida y la mirada sigue a la cadera.",
      "Dejar caer el peso en la bajada.",
    ],
    senales: "Glúteo a tope en los últimos centímetros. Si solo lo notas en los cuádriceps, acerca los pies al cuerpo.",
    cuidado: "Sin almohadilla gruesa deja moratón. Si no hay, cambia a la máquina o al multipower.",
    sustitutos: [
      { id: "hip-thrust-maquina", motivo: "ocupada" },
      { id: "hip-thrust-multipower", motivo: "ocupada" },
      { id: "puente-gluteo-suelo", motivo: "casa" },
    ],
    imagen: null,
    video: null,
  },
  {
    id: "hip-thrust-multipower",
    nombre: "Hip thrust en multipower",
    alias: ["hip thrust smith", "empuje de cadera en smith"],
    grupo: "gluteo",
    secundarios: ["femoral"],
    material: "multipower",
    patron: "empuje-cadera",
    nivel: "inicia",
    pasos: [
      "Coloca el banco centrado bajo la barra y siéntate con la espalda en el banco.",
      "Baja la barra hasta la cadera con la almohadilla puesta y desengánchala.",
      "Empuja con los talones hasta la línea recta y aprieta arriba un segundo.",
      "Baja hasta casi tocar el suelo con la cadera, sin descansar.",
    ],
    ajuste: [
      "Barra a la altura de la cadera cuando estés sentada en el suelo.",
      "Banco centrado: si queda torcido, un lado trabaja más.",
      "Comprueba el tope de seguridad antes de la primera serie.",
    ],
    errores: [
      "Dejar la barra sobre el hueso sin almohadilla.",
      "Separar demasiado los pies y perder el empuje del talón.",
    ],
    senales: "Es la versión más fácil de controlar: si puedes repetir el mismo recorrido serie tras serie, está bien puesta.",
    cuidado: null,
    sustitutos: [
      { id: "hip-thrust-maquina", motivo: "ocupada" },
      { id: "hip-thrust-barra", motivo: "ocupada" },
      { id: "puente-gluteo-suelo", motivo: "casa" },
    ],
    imagen: null,
    video: null,
  },
  {
    id: "puente-gluteo-suelo",
    nombre: "Puente de glúteo en el suelo",
    alias: ["puente de glúteo", "glute bridge", "elevación de cadera en suelo"],
    grupo: "gluteo",
    secundarios: ["femoral"],
    material: "peso-corporal",
    patron: "empuje-cadera",
    nivel: "inicia",
    pasos: [
      "Túmbate boca arriba, rodillas dobladas y pies a la anchura de la cadera.",
      "Mete un poco la pelvis para que la lumbar toque el suelo.",
      "Sube la cadera apretando el glúteo hasta la línea recta rodilla-hombro.",
      "Aguanta un segundo arriba y baja sin descansar del todo.",
    ],
    ajuste: [],
    errores: [
      "Subir arqueando la lumbar en vez de apretar el glúteo.",
      "Pies demasiado lejos: entonces trabaja el femoral.",
    ],
    senales: "Glúteo ardiendo en las últimas repeticiones. En casa, con una mochila o un disco encima de la cadera, sirve perfectamente.",
    cuidado: null,
    sustitutos: [
      { id: "hip-thrust-maquina", motivo: "sin-maquina" },
      { id: "hip-thrust-una-pierna", motivo: "mas-dificil" },
    ],
    imagen: null,
    video: null,
  },
  {
    id: "hip-thrust-una-pierna",
    nombre: "Empuje de cadera a una pierna",
    alias: ["hip thrust unilateral", "puente a una pierna"],
    grupo: "gluteo",
    secundarios: ["femoral", "core"],
    material: "peso-corporal",
    patron: "empuje-cadera",
    nivel: "media",
    pasos: [
      "Espalda apoyada en el banco o en el suelo, un pie plantado y el otro levantado.",
      "Mete la pelvis y sube con el talón de la pierna de apoyo.",
      "Arriba, cadera recta: sin dejar que un lado caiga.",
      "Baja controlando y cambia de pierna al terminar las repeticiones.",
    ],
    ajuste: [],
    errores: [
      "Girar la cadera hacia el lado libre.",
      "Empujar con la punta del pie en vez del talón.",
    ],
    senales: "Un glúteo solo, y se nota la diferencia entre lados. Esa diferencia es justo lo que viene a corregir.",
    cuidado: null,
    sustitutos: [
      { id: "puente-gluteo-suelo", motivo: "mas-facil" },
      { id: "hip-thrust-maquina", motivo: "sin-maquina" },
    ],
    imagen: null,
    video: null,
  },
  {
    id: "patada-gluteo-polea",
    nombre: "Patada de glúteo en polea",
    alias: ["kickback", "patada de glúteo", "extensión de cadera en polea"],
    grupo: "gluteo",
    secundarios: ["femoral"],
    material: "polea",
    patron: "aislamiento",
    nivel: "inicia",
    pasos: [
      "Tobillera puesta y polea abajo del todo. De pie, frente a la torre, agarrada.",
      "Inclina un poco el tronco y mantén el abdomen firme.",
      "Lleva la pierna atrás apretando el glúteo, sin arquear la espalda.",
      "Vuelve despacio hasta notar el estiramiento.",
    ],
    ajuste: [
      "Polea en el agujero más bajo.",
      "Tobillera por encima del hueso del tobillo, bien ceñida.",
      "Un paso atrás para que el cable tenga tensión desde el principio.",
    ],
    errores: [
      "Tirar con la lumbar: si la espalda se arquea, el glúteo ha dejado de trabajar.",
      "Peso de más y recorrido de nada.",
    ],
    senales: "Quemazón arriba y afuera del glúteo. La espalda no debería notarse.",
    cuidado: null,
    sustitutos: [
      { id: "patada-gluteo-cuadrupedia", motivo: "casa" },
      { id: "abductores-maquina", motivo: "ocupada" },
    ],
    imagen: null,
    video: null,
  },
  {
    id: "patada-gluteo-cuadrupedia",
    nombre: "Patada de glúteo en cuadrupedia",
    alias: ["patada en cuatro apoyos", "donkey kick"],
    grupo: "gluteo",
    secundarios: ["core"],
    material: "peso-corporal",
    patron: "aislamiento",
    nivel: "inicia",
    pasos: [
      "A cuatro patas, manos debajo de los hombros y rodillas debajo de la cadera.",
      "Abdomen firme y espalda plana, como una mesa.",
      "Sube una pierna doblada llevando el talón al techo, sin pasar de la línea de la espalda.",
      "Baja sin apoyar y repite.",
    ],
    ajuste: [],
    errores: [
      "Subir tanto que la espalda se arquea.",
      "Girar la cadera para llegar más alto.",
    ],
    senales: "Si la espalda se mueve, estás subiendo de más. Con una banda por encima de la rodilla se nota el doble.",
    cuidado: null,
    sustitutos: [
      { id: "patada-gluteo-polea", motivo: "sin-maquina" },
      { id: "puente-gluteo-suelo", motivo: "casa" },
    ],
    imagen: null,
    video: null,
  },
  {
    id: "abductores-maquina",
    nombre: "Abductores en máquina",
    alias: ["abducción de cadera", "máquina de abductores", "aperturas de pierna"],
    grupo: "gluteo",
    secundarios: [],
    material: "maquina",
    patron: "aislamiento",
    nivel: "inicia",
    pasos: [
      "Siéntate con la espalda apoyada y las rodillas por dentro de los topes.",
      "Abre las piernas apretando por fuera del glúteo.",
      "Aguanta medio segundo en el punto más abierto.",
      "Cierra despacio, sin dejar que el peso te empuje.",
    ],
    ajuste: [
      "Apertura de inicio: la justa para no notar tirón en la ingle.",
      "Respaldo recto para trabajar más el glúteo medio; inclinada hacia delante, también.",
    ],
    errores: [
      "Ir a tirones y usar el impulso del tronco.",
      "Soltar el peso de golpe al cerrar.",
    ],
    senales: "Quemazón en la parte de arriba y de fuera del glúteo, el que redondea la cadera.",
    cuidado: null,
    sustitutos: [
      { id: "paseo-lateral-banda", motivo: "casa" },
      { id: "patada-gluteo-polea", motivo: "ocupada" },
    ],
    imagen: null,
    video: null,
  },
  {
    id: "paseo-lateral-banda",
    nombre: "Paseo lateral con banda",
    alias: ["monster walk", "caminata lateral con banda", "banda tobillos"],
    grupo: "gluteo",
    secundarios: ["core"],
    material: "banda",
    patron: "aislamiento",
    nivel: "inicia",
    pasos: [
      "Banda por encima de las rodillas o en los tobillos.",
      "Media sentadilla, pecho arriba y abdomen firme.",
      "Da pasos laterales sin juntar los pies del todo.",
      "Haz el mismo número de pasos hacia cada lado.",
    ],
    ajuste: [],
    errores: [
      "Levantarse de la media sentadilla a mitad de serie.",
      "Dejar que la rodilla se meta hacia dentro.",
    ],
    senales: "Arde por fuera del glúteo. Es el ejercicio de calentamiento que más cambia una sesión de pierna.",
    cuidado: null,
    sustitutos: [{ id: "abductores-maquina", motivo: "sin-maquina" }],
    imagen: null,
    video: null,
  },

  /* ---- Cuádriceps y dominantes de rodilla ------------------------------ */
  {
    id: "prensa-45",
    nombre: "Prensa inclinada",
    alias: ["prensa", "leg press", "prensa 45"],
    grupo: "cuadriceps",
    secundarios: ["gluteo", "femoral"],
    material: "maquina",
    patron: "rodilla",
    nivel: "inicia",
    pasos: [
      "Siéntate con la espalda y la cadera pegadas al respaldo.",
      "Pies a la anchura de la cadera en el centro de la plataforma, punta ligeramente hacia fuera.",
      "Baja hasta que la rodilla quede en ángulo recto, sin que la lumbar se despegue.",
      "Empuja con todo el pie, sin bloquear la rodilla del todo arriba.",
    ],
    ajuste: [
      "Respaldo: cuanto más tumbado, más recorrido; empieza en la posición media.",
      "Seguros puestos antes de cargar discos.",
      "Pies en el centro: subirlos mete más glúteo, bajarlos mete más cuádriceps.",
    ],
    errores: [
      "Despegar la cadera del respaldo abajo: ahí se carga la lumbar.",
      "Bloquear la rodilla de golpe arriba.",
      "Rango corto con mucho peso.",
    ],
    senales: "Cuádriceps a tope y espalda tranquila. Si la lumbar se despega, has bajado de más.",
    cuidado: "Con molestia de rodilla: menos recorrido y pies un poco más altos.",
    sustitutos: [
      { id: "prensa-pies-altos", motivo: "mas-facil" },
      { id: "sentadilla-goblet", motivo: "ocupada" },
      { id: "sentadilla-multipower", motivo: "ocupada" },
    ],
    imagen: null,
    video: null,
  },
  {
    id: "prensa-pies-altos",
    nombre: "Prensa con pies altos",
    alias: ["prensa pies altos", "leg press pies altos"],
    grupo: "gluteo",
    secundarios: ["cuadriceps", "femoral"],
    material: "maquina",
    patron: "rodilla",
    nivel: "inicia",
    pasos: [
      "Igual que la prensa, pero con los pies en la parte alta de la plataforma.",
      "Pies a la anchura de la cadera o un poco más.",
      "Baja controlando hasta donde la cadera no se despegue.",
      "Empuja con el talón, no con la punta.",
    ],
    ajuste: [
      "Pies altos: el talón cerca del borde de arriba.",
      "Si notas tirón detrás de la rodilla, baja un poco los pies.",
    ],
    errores: [
      "Empujar con la punta del pie.",
      "Bajar tanto que la cadera se enrolla.",
    ],
    senales: "Reparte a glúteo y femoral: es la versión que mejor va cuando la rodilla está sensible.",
    cuidado: null,
    sustitutos: [
      { id: "prensa-45", motivo: "mas-dificil" },
      { id: "hip-thrust-maquina", motivo: "ocupada" },
    ],
    imagen: null,
    video: null,
  },
  {
    id: "sentadilla-barra",
    nombre: "Sentadilla con barra",
    alias: ["sentadilla", "squat", "sentadilla trasera"],
    grupo: "cuadriceps",
    secundarios: ["gluteo", "core"],
    material: "barra",
    patron: "rodilla",
    nivel: "avanzada",
    pasos: [
      "Barra apoyada en la parte alta de la espalda, no en el cuello.",
      "Pies a la anchura de los hombros, punta ligeramente hacia fuera.",
      "Coge aire, aprieta el abdomen y baja llevando la cadera atrás y abajo a la vez.",
      "Sube empujando el suelo, sin que la cadera salga antes que el pecho.",
    ],
    ajuste: [],
    errores: [
      "Levantar los talones del suelo.",
      "Que suba primero la cadera y el pecho se quede abajo.",
      "Perder el aire a mitad de la subida.",
    ],
    senales: "Pierna entera y abdomen firme. Si la espalda baja se redondea abajo, has pasado tu rango: para ahí.",
    cuidado: "Es el ejercicio con más técnica del plan. Si hay molestia de rodilla o lumbar, usamos goblet o multipower.",
    sustitutos: [
      { id: "sentadilla-goblet", motivo: "mas-facil" },
      { id: "sentadilla-multipower", motivo: "rodilla" },
      { id: "prensa-45", motivo: "lumbar" },
    ],
    imagen: null,
    video: null,
  },
  {
    id: "sentadilla-goblet",
    nombre: "Sentadilla goblet",
    alias: ["goblet squat", "sentadilla con mancuerna"],
    grupo: "cuadriceps",
    secundarios: ["gluteo", "core"],
    material: "mancuerna",
    patron: "rodilla",
    nivel: "inicia",
    pasos: [
      "Sujeta la mancuerna o kettlebell contra el pecho, con los codos dentro.",
      "Pies a la anchura de los hombros.",
      "Baja entre las rodillas manteniendo el pecho alto.",
      "Sube empujando el suelo y aprieta el glúteo arriba.",
    ],
    ajuste: [],
    errores: [
      "Dejar caer los codos y redondear la espalda.",
      "Rodillas hacia dentro al subir.",
    ],
    senales: "Es la mejor para aprender el movimiento: el peso delante te obliga a mantener el pecho alto.",
    cuidado: null,
    sustitutos: [
      { id: "sentadilla-barra", motivo: "mas-dificil" },
      { id: "prensa-45", motivo: "ocupada" },
    ],
    imagen: null,
    video: null,
  },
  {
    id: "sentadilla-multipower",
    nombre: "Sentadilla en multipower",
    alias: ["sentadilla smith", "squat multipower"],
    grupo: "cuadriceps",
    secundarios: ["gluteo"],
    material: "multipower",
    patron: "rodilla",
    nivel: "inicia",
    pasos: [
      "Barra en la parte alta de la espalda y pies un paso por delante de la barra.",
      "Desengancha girando la muñeca y baja con la espalda recta.",
      "Baja hasta la rodilla en ángulo recto o un poco más.",
      "Sube empujando con todo el pie.",
    ],
    ajuste: [
      "Barra a la altura de la clavícula para engancharla sin ponerte de puntillas.",
      "Seguros un palmo por debajo de tu punto más bajo.",
      "Pies por delante: cuanto más adelantados, más glúteo.",
    ],
    errores: [
      "Pies debajo de la barra: así carga toda la rodilla.",
      "Olvidarse de poner los seguros.",
    ],
    senales: "Como la barra va guiada, puedes centrarte en bajar bien. Es la opción segura para entrenar sola.",
    cuidado: null,
    sustitutos: [
      { id: "sentadilla-goblet", motivo: "sin-maquina" },
      { id: "prensa-45", motivo: "ocupada" },
    ],
    imagen: null,
    video: null,
  },
  {
    id: "zancada-mancuernas",
    nombre: "Zancadas con mancuernas",
    alias: ["zancadas", "lunges", "desplantes"],
    grupo: "cuadriceps",
    secundarios: ["gluteo", "core"],
    material: "mancuerna",
    patron: "rodilla",
    nivel: "media",
    pasos: [
      "Una mancuerna en cada mano, brazos relajados.",
      "Da un paso largo al frente y baja la rodilla de atrás hacia el suelo.",
      "El peso, en el talón de la pierna de delante.",
      "Empuja para volver y cambia de pierna.",
    ],
    ajuste: [],
    errores: [
      "Paso corto: la rodilla se va delante del pie.",
      "Inclinar el tronco hacia delante.",
    ],
    senales: "Glúteo de la pierna de delante. Si solo notas la rodilla, alarga el paso.",
    cuidado: "Si la rodilla molesta, cámbialas por zancada hacia atrás o quítalas del plan esa semana.",
    sustitutos: [
      { id: "bulgara", motivo: "mas-dificil" },
      { id: "prensa-pies-altos", motivo: "rodilla" },
      { id: "step-up-cajon", motivo: "casa" },
    ],
    imagen: null,
    video: null,
  },
  {
    id: "bulgara",
    nombre: "Sentadilla búlgara",
    alias: ["búlgara", "bulgarian split squat", "zancada búlgara"],
    grupo: "cuadriceps",
    secundarios: ["gluteo", "core"],
    material: "mancuerna",
    patron: "rodilla",
    nivel: "avanzada",
    pasos: [
      "Pon el empeine del pie de atrás en el banco.",
      "El pie de delante, lo bastante lejos para que la rodilla no pase del pie al bajar.",
      "Baja recto, como un ascensor, hasta que la rodilla de atrás casi toque.",
      "Sube empujando con el talón de delante.",
    ],
    ajuste: [],
    errores: [
      "Pie de delante demasiado cerca del banco.",
      "Perder el equilibrio por mirar al suelo: mira a un punto fijo al frente.",
    ],
    senales: "Es dura y eso es normal. Si te tiembla la pierna de apoyo, estás justo donde toca.",
    cuidado: "Con molestia de rodilla, inclínate un poco hacia delante para llevarla a glúteo.",
    sustitutos: [
      { id: "zancada-mancuernas", motivo: "mas-facil" },
      { id: "prensa-pies-altos", motivo: "rodilla" },
    ],
    imagen: null,
    video: null,
  },
  {
    id: "step-up-cajon",
    nombre: "Subida al cajón",
    alias: ["step up", "subidas al banco"],
    grupo: "gluteo",
    secundarios: ["cuadriceps", "core"],
    material: "peso-corporal",
    patron: "rodilla",
    nivel: "inicia",
    pasos: [
      "Cajón o banco a la altura de la rodilla.",
      "Sube apoyando todo el pie y empujando con el talón.",
      "Sube sin dar impulso con la pierna de abajo.",
      "Baja controlando, sin dejarte caer.",
    ],
    ajuste: [],
    errores: [
      "Impulsarse con la pierna de abajo.",
      "Cajón demasiado alto y ayuda del tronco.",
    ],
    senales: "Glúteo de la pierna de arriba. Con mancuernas en las manos sube de nivel enseguida.",
    cuidado: null,
    sustitutos: [
      { id: "zancada-mancuernas", motivo: "mas-dificil" },
      { id: "prensa-45", motivo: "sin-maquina" },
    ],
    imagen: null,
    video: null,
  },
  {
    id: "extension-cuadriceps",
    nombre: "Extensión de cuádriceps",
    alias: ["extensiones de cuádriceps", "leg extension", "cuádriceps en máquina"],
    grupo: "cuadriceps",
    secundarios: [],
    material: "maquina",
    patron: "aislamiento",
    nivel: "inicia",
    pasos: [
      "Siéntate con la espalda apoyada y la rodilla alineada con el eje de giro.",
      "Rodillo por encima del tobillo, no sobre el pie.",
      "Estira hasta arriba y aguanta medio segundo.",
      "Baja despacio, sin soltar el peso de golpe.",
    ],
    ajuste: [
      "Respaldo: la rodilla justo en el eje de la máquina.",
      "Rodillo: encima del tobillo.",
      "Tope de rango: si la rodilla molesta, empieza desde menos flexión.",
    ],
    errores: [
      "Dar tirones con la cadera para subir.",
      "Dejar caer el peso en la bajada, que es donde está la mitad del trabajo.",
    ],
    senales: "Cuádriceps aislado y ardiendo. No debería notarse dentro de la rodilla.",
    cuidado: "Si hay condromalacia o molestia rotuliana, se trabaja en rango corto y con poco peso.",
    sustitutos: [
      { id: "prensa-45", motivo: "ocupada" },
      { id: "sentadilla-goblet", motivo: "sin-maquina" },
    ],
    imagen: null,
    video: null,
  },

  /* ---- Femoral y bisagra de cadera -------------------------------------- */
  {
    id: "peso-muerto-rumano",
    nombre: "Peso muerto rumano",
    alias: ["rumano", "romanian deadlift", "peso muerto piernas rectas"],
    grupo: "femoral",
    secundarios: ["gluteo", "espalda"],
    material: "barra",
    patron: "bisagra",
    nivel: "media",
    pasos: [
      "De pie, barra pegada al cuerpo y rodillas ligeramente dobladas.",
      "Lleva la cadera atrás como si cerraras una puerta con el culo.",
      "Baja la barra rozando el muslo hasta notar el estiramiento detrás.",
      "Sube apretando el glúteo, sin echar la cadera hacia delante de más.",
    ],
    ajuste: [],
    errores: [
      "Doblar la espalda en vez de la cadera.",
      "Separar la barra del cuerpo.",
      "Bajar más de lo que da el estiramiento.",
    ],
    senales: "Tirón detrás del muslo, no en la espalda baja. Si la lumbar es lo que más se nota, has perdido la posición.",
    cuidado: "Con molestia lumbar, se cambia por curl femoral tumbada hasta que pase.",
    sustitutos: [
      { id: "rumano-mancuernas", motivo: "ocupada" },
      { id: "curl-femoral-tumbada", motivo: "lumbar" },
      { id: "buenos-dias", motivo: "sin-maquina" },
    ],
    imagen: null,
    video: null,
  },
  {
    id: "rumano-mancuernas",
    nombre: "Peso muerto rumano con mancuernas",
    alias: ["rumano con mancuernas", "rdl mancuernas"],
    grupo: "femoral",
    secundarios: ["gluteo"],
    material: "mancuerna",
    patron: "bisagra",
    nivel: "inicia",
    pasos: [
      "Una mancuerna en cada mano, delante del muslo.",
      "Rodillas un poco dobladas y cadera atrás.",
      "Baja las mancuernas pegadas a la pierna hasta el estiramiento.",
      "Sube apretando el glúteo.",
    ],
    ajuste: [],
    errores: [
      "Alejar las mancuernas del cuerpo.",
      "Convertirlo en una sentadilla doblando mucho la rodilla.",
    ],
    senales: "Igual que con barra pero más fácil de colocar: es la versión para aprender el movimiento.",
    cuidado: null,
    sustitutos: [
      { id: "peso-muerto-rumano", motivo: "mas-dificil" },
      { id: "curl-femoral-tumbada", motivo: "lumbar" },
    ],
    imagen: null,
    video: null,
  },
  {
    id: "curl-femoral-tumbada",
    nombre: "Curl femoral tumbada",
    alias: ["curl femoral", "femoral tumbada", "leg curl"],
    grupo: "femoral",
    secundarios: ["gemelo"],
    material: "maquina",
    patron: "aislamiento",
    nivel: "inicia",
    pasos: [
      "Túmbate boca abajo con la rodilla justo al borde del banco.",
      "Rodillo por encima del talón, no sobre el gemelo.",
      "Lleva el talón al glúteo y aprieta arriba.",
      "Baja despacio sin que el peso toque la pila.",
    ],
    ajuste: [
      "Eje de la máquina alineado con la rodilla.",
      "Rodillo por encima del talón.",
      "Agárrate a las asas para no despegar la cadera.",
    ],
    errores: [
      "Levantar la cadera del banco para ayudarte.",
      "Ir a tirones.",
    ],
    senales: "Femoral trabajando solo. La cadera no se mueve del banco.",
    cuidado: null,
    sustitutos: [
      { id: "curl-femoral-sentada", motivo: "ocupada" },
      { id: "rumano-mancuernas", motivo: "sin-maquina" },
    ],
    imagen: null,
    video: null,
  },
  {
    id: "curl-femoral-sentada",
    nombre: "Curl femoral sentada",
    alias: ["femoral sentada", "seated leg curl"],
    grupo: "femoral",
    secundarios: [],
    material: "maquina",
    patron: "aislamiento",
    nivel: "inicia",
    pasos: [
      "Siéntate con la espalda apoyada y la rodilla en el eje de la máquina.",
      "Rodillo por encima del talón y almohadilla del muslo bien apretada.",
      "Dobla la rodilla llevando el talón debajo del asiento.",
      "Vuelve despacio hasta casi estirar.",
    ],
    ajuste: [
      "Respaldo: rodilla en el eje.",
      "Almohadilla del muslo apretada: si el muslo se levanta, está floja.",
    ],
    errores: [
      "Dejar la almohadilla suelta.",
      "Echar el cuerpo hacia delante para tirar.",
    ],
    senales: "Estira más el femoral que la versión tumbada. Suele notarse más.",
    cuidado: null,
    sustitutos: [
      { id: "curl-femoral-tumbada", motivo: "ocupada" },
      { id: "rumano-mancuernas", motivo: "sin-maquina" },
    ],
    imagen: null,
    video: null,
  },
  {
    id: "buenos-dias",
    nombre: "Buenos días con barra",
    alias: ["good morning", "buenos dias"],
    grupo: "femoral",
    secundarios: ["gluteo", "espalda"],
    material: "barra",
    patron: "bisagra",
    nivel: "avanzada",
    pasos: [
      "Barra en la parte alta de la espalda, como en sentadilla.",
      "Rodillas ligeramente dobladas y abdomen firme.",
      "Lleva la cadera atrás bajando el pecho hasta notar el estiramiento.",
      "Sube apretando el glúteo, sin redondear la espalda en ningún momento.",
    ],
    ajuste: [],
    errores: [
      "Bajar más de lo que da el femoral y redondear la espalda.",
      "Usar demasiado peso: aquí se va ligero.",
    ],
    senales: "Femoral y glúteo. Es un ejercicio técnico: si no lo controlas, mejor rumano.",
    cuidado: "Fuera del plan si hay cualquier molestia lumbar.",
    sustitutos: [
      { id: "peso-muerto-rumano", motivo: "mas-facil" },
      { id: "curl-femoral-tumbada", motivo: "lumbar" },
    ],
    imagen: null,
    video: null,
  },
  {
    id: "hiperextensiones",
    nombre: "Hiperextensiones a 45º",
    alias: ["lumbares", "extensiones lumbares", "banco romano", "hiperextensiones"],
    grupo: "femoral",
    secundarios: ["gluteo", "espalda"],
    material: "maquina",
    patron: "bisagra",
    nivel: "inicia",
    pasos: [
      "Almohadilla justo debajo de la cadera, no sobre el muslo.",
      "Cruza los brazos en el pecho y mete la barbilla.",
      "Baja doblando por la cadera con la espalda recta.",
      "Sube hasta la línea del cuerpo apretando el glúteo, sin pasarte.",
    ],
    ajuste: [
      "Almohadilla: el borde de arriba justo debajo del hueso de la cadera.",
      "Pies bien sujetos y piernas estiradas.",
    ],
    errores: [
      "Subir más allá de la línea del cuerpo y arquear la espalda.",
      "Coger carrerilla con el tronco.",
    ],
    senales: "Glúteo y femoral. Si acaba cargando la lumbar, estás subiendo de más.",
    cuidado: null,
    sustitutos: [
      { id: "rumano-mancuernas", motivo: "ocupada" },
      { id: "puente-gluteo-suelo", motivo: "casa" },
    ],
    imagen: null,
    video: null,
  },

  /* ---- Gemelo ----------------------------------------------------------- */
  {
    id: "gemelos-prensa",
    nombre: "Gemelos en prensa",
    alias: ["gemelos", "elevación de talones en prensa", "calf press"],
    grupo: "gemelo",
    secundarios: [],
    material: "maquina",
    patron: "aislamiento",
    nivel: "inicia",
    pasos: [
      "Pon la punta de los pies en el borde de abajo de la plataforma.",
      "Rodillas casi estiradas, pero sin bloquear.",
      "Empuja con la punta hasta arriba del todo y aguanta un segundo.",
      "Baja despacio hasta notar el estiramiento.",
    ],
    ajuste: [
      "Seguros puestos: con los pies solo en la punta, no se baja el peso con las piernas.",
      "Media plataforma fuera: solo la punta apoyada.",
    ],
    errores: [
      "Recorrido mínimo con mucho peso.",
      "Doblar la rodilla para ayudarse.",
    ],
    senales: "Quemazón en el gemelo. Es un músculo que pide recorrido completo y muchas repeticiones.",
    cuidado: null,
    sustitutos: [
      { id: "gemelos-de-pie", motivo: "ocupada" },
    ],
    imagen: null,
    video: null,
  },
  {
    id: "gemelos-de-pie",
    nombre: "Elevación de talones de pie",
    alias: ["gemelos de pie", "elevación de talones"],
    grupo: "gemelo",
    secundarios: [],
    material: "peso-corporal",
    patron: "aislamiento",
    nivel: "inicia",
    pasos: [
      "De pie, punta de los pies en un escalón y talón en el aire.",
      "Sube hasta ponerte de puntillas del todo.",
      "Aguanta arriba un segundo.",
      "Baja despacio hasta el estiramiento.",
    ],
    ajuste: [],
    errores: ["Rebotar abajo en vez de controlar."],
    senales: "Sirve en casa y en cualquier gimnasio. Con una mancuerna en la mano, sube de nivel.",
    cuidado: null,
    sustitutos: [{ id: "gemelos-prensa", motivo: "mas-dificil" }],
    imagen: null,
    video: null,
  },
];
