/**
 * Tren superior y core, segunda tanda.
 *
 * Aquí entran las máquinas que tiene cualquier gimnasio y que no estaban en la
 * primera: remo con pecho apoyado, contractora, poleas cruzadas. Son las que
 * permiten montar un día de torso completo sin repetir dos veces el mismo
 * ángulo.
 */

import type { Ejercicio } from "../ejercicios";

export const SUPERIOR_2: Ejercicio[] = [
  {
    id: "remo-maquina-pecho-apoyado",
    nombre: "Remo en máquina con pecho apoyado",
    alias: ["remo máquina", "remo pecho apoyado", "chest supported row"],
    grupo: "espalda",
    secundarios: ["brazo"],
    material: "maquina",
    patron: "traccion-horizontal",
    nivel: "inicia",
    pasos: [
      "Pecho apoyado en el respaldo y pies firmes.",
      "Agarra las asas con los brazos estirados.",
      "Tira llevando los codos atrás, juntando los omóplatos.",
      "Vuelve despacio hasta estirar del todo.",
    ],
    ajuste: [
      "Asiento: las asas a la altura del pecho, no de la cara.",
      "Pecho pegado al respaldo todo el recorrido.",
    ],
    errores: [
      "Despegar el pecho para tirar más.",
      "Encoger los hombros.",
    ],
    senales: "Como el pecho va apoyado, la lumbar no participa: es el remo seguro cuando la espalda baja está tocada.",
    cuidado: null,
    sustitutos: [
      { id: "remo-polea-baja", motivo: "ocupada" },
      { id: "remo-mancuerna", motivo: "sin-maquina" },
    ],
    imagen: null,
    video: null,
  },
  {
    id: "jalon-agarre-neutro",
    nombre: "Jalón con agarre neutro",
    alias: ["jalón neutro", "jalón agarre estrecho", "jalón triángulo"],
    grupo: "espalda",
    secundarios: ["brazo"],
    material: "polea",
    patron: "traccion-vertical",
    nivel: "inicia",
    pasos: [
      "Agarre en triángulo o paralelo, palmas mirándose.",
      "Muslos bien sujetos bajo el rodillo.",
      "Tira al pecho llevando los codos abajo y pegados.",
      "Sube despacio hasta estirar.",
    ],
    ajuste: [
      "Rodillo apretado sobre el muslo.",
      "Agarre neutro: el que menos molesta al hombro.",
    ],
    errores: [
      "Echar el cuerpo atrás.",
      "Parar a mitad de camino al subir.",
    ],
    senales: "Trabaja más el centro de la espalda que el jalón ancho, y es el que mejor va si el hombro se queja.",
    cuidado: null,
    sustitutos: [
      { id: "jalon-al-pecho", motivo: "ocupada" },
      { id: "remo-polea-baja", motivo: "hombro" },
    ],
    imagen: null,
    video: null,
  },
  {
    id: "pull-over-polea",
    nombre: "Pull over en polea",
    alias: ["pullover", "pull over en polea alta"],
    grupo: "espalda",
    secundarios: ["pecho"],
    material: "polea",
    patron: "aislamiento",
    nivel: "media",
    pasos: [
      "Polea alta con barra o cuerda, de pie y un paso atrás.",
      "Inclina un poco el tronco, brazos casi estirados.",
      "Baja los brazos hasta los muslos sin doblar el codo.",
      "Vuelve despacio notando el estiramiento del dorsal.",
    ],
    ajuste: [
      "Polea arriba del todo.",
      "Distancia: la que mantenga tensión arriba.",
    ],
    errores: [
      "Doblar el codo y convertirlo en tríceps.",
      "Mover el tronco para ayudarse.",
    ],
    senales: "Debajo de la axila, en el dorsal. Si lo notas en el tríceps, estás doblando el codo.",
    cuidado: null,
    sustitutos: [{ id: "jalon-al-pecho", motivo: "ocupada" }],
    imagen: null,
    video: null,
  },
  {
    id: "press-banca-barra",
    nombre: "Press de banca con barra",
    alias: ["press banca", "bench press", "press plano"],
    grupo: "pecho",
    secundarios: ["hombro", "brazo"],
    material: "barra",
    patron: "empuje-horizontal",
    nivel: "media",
    pasos: [
      "Túmbate con los ojos debajo de la barra y los pies firmes.",
      "Agarre algo más ancho que los hombros, muñeca recta.",
      "Baja la barra al centro del pecho con los codos a 45º.",
      "Empuja sin despegar la cadera del banco.",
    ],
    ajuste: [],
    errores: [
      "Rebotar la barra en el pecho.",
      "Codos totalmente abiertos.",
      "Despegar la cadera para sacar la última repetición.",
    ],
    senales: "Pecho. Con barra se puede ir más pesada que con mancuernas, pero hace falta alguien que vigile o los seguros puestos.",
    cuidado: "Sin ayuda, mejor mancuernas o máquina: una barra atascada en el pecho es el accidente más típico del gimnasio.",
    sustitutos: [
      { id: "press-banca-mancuernas", motivo: "sin-maquina" },
      { id: "press-pecho-maquina", motivo: "hombro" },
    ],
    imagen: null,
    video: null,
  },
  {
    id: "press-pecho-maquina",
    nombre: "Press de pecho en máquina",
    alias: ["press en máquina", "chest press"],
    grupo: "pecho",
    secundarios: ["brazo", "hombro"],
    material: "maquina",
    patron: "empuje-horizontal",
    nivel: "inicia",
    pasos: [
      "Siéntate con la espalda apoyada y las asas a la altura del pecho.",
      "Empuja hacia delante sin bloquear el codo del todo.",
      "Vuelve controlando hasta notar el estiramiento.",
      "Mantén los hombros abajo, lejos de las orejas.",
    ],
    ajuste: [
      "Asiento: las asas a la altura media del pecho.",
      "Respaldo pegado a la espalda.",
    ],
    errores: [
      "Asiento demasiado bajo, que lleva el trabajo al hombro.",
      "Sacar los hombros hacia delante al empujar.",
    ],
    senales: "Es el empuje seguro para entrenar sola e ir pesada sin riesgo.",
    cuidado: null,
    sustitutos: [
      { id: "press-banca-mancuernas", motivo: "ocupada" },
      { id: "flexiones", motivo: "casa" },
    ],
    imagen: null,
    video: null,
  },
  {
    id: "cruces-polea",
    nombre: "Cruces en polea",
    alias: ["cruces", "aperturas en polea", "cable crossover"],
    grupo: "pecho",
    secundarios: [],
    material: "polea",
    patron: "aislamiento",
    nivel: "media",
    pasos: [
      "Una polea a cada lado, a la altura del hombro o algo más arriba.",
      "Un paso al frente, tronco ligeramente inclinado.",
      "Junta las manos delante del pecho describiendo un arco.",
      "Abre despacio hasta notar el estiramiento.",
    ],
    ajuste: [
      "Altura: a la altura del hombro para el centro del pecho; arriba para la parte baja.",
      "Un paso al frente para tener tensión en todo el recorrido.",
    ],
    errores: [
      "Doblar y estirar el codo como si fuera un press.",
      "Peso de más y recorrido mínimo.",
    ],
    senales: "Estira el pecho más que ninguna máquina. Va perfecto al final del día de torso.",
    cuidado: null,
    sustitutos: [
      { id: "aperturas-maquina", motivo: "ocupada" },
      { id: "press-banca-mancuernas", motivo: "sin-maquina" },
    ],
    imagen: null,
    video: null,
  },
  {
    id: "pajaros-posterior",
    nombre: "Pájaros para hombro posterior",
    alias: ["pájaros", "elevaciones posteriores", "rear delt fly"],
    grupo: "hombro",
    secundarios: ["espalda"],
    material: "mancuerna",
    patron: "aislamiento",
    nivel: "inicia",
    pasos: [
      "Sentada en el borde del banco, tronco inclinado sobre los muslos.",
      "Mancuernas colgando, codos muy ligeramente doblados.",
      "Abre los brazos a los lados, guiando con el codo.",
      "Baja despacio.",
    ],
    ajuste: [],
    errores: [
      "Levantar el tronco para subir más.",
      "Juntar los omóplatos en vez de abrir los brazos.",
    ],
    senales: "Parte de atrás del hombro. Es poco peso y mucho control: lo que equilibra tanto empuje.",
    cuidado: null,
    sustitutos: [{ id: "face-pull", motivo: "sin-maquina" }],
    imagen: null,
    video: null,
  },
  {
    id: "curl-predicador",
    nombre: "Curl en banco predicador",
    alias: ["predicador", "curl scott", "banco scott"],
    grupo: "brazo",
    secundarios: [],
    material: "maquina",
    patron: "aislamiento",
    nivel: "inicia",
    pasos: [
      "Axilas apoyadas en la parte alta del soporte.",
      "Brazos pegados al apoyo todo el recorrido.",
      "Sube sin despegar el codo.",
      "Baja hasta casi estirar, controlando.",
    ],
    ajuste: [
      "Asiento: la axila justo en el borde de arriba del soporte.",
      "Si el codo se despega al bajar, el asiento está bajo.",
    ],
    errores: [
      "Despegar los codos del apoyo.",
      "Soltar el peso de golpe al final.",
    ],
    senales: "Bíceps aislado de verdad: aquí no se puede hacer trampa con el cuerpo.",
    cuidado: "Bajar hasta el bloqueo con mucho peso es donde se lesiona el codo: baja controlando.",
    sustitutos: [
      { id: "curl-biceps-mancuernas", motivo: "ocupada" },
      { id: "curl-martillo", motivo: "sin-maquina" },
    ],
    imagen: null,
    video: null,
  },
  {
    id: "press-frances",
    nombre: "Press francés",
    alias: ["francés", "skull crusher", "extensión de tríceps tumbada"],
    grupo: "brazo",
    secundarios: [],
    material: "barra",
    patron: "aislamiento",
    nivel: "media",
    pasos: [
      "Tumbada, barra Z arriba con los brazos estirados.",
      "Dobla solo el codo, llevando la barra hacia la frente.",
      "Los codos se quedan quietos, apuntando al techo.",
      "Sube estirando sin bloquear de golpe.",
    ],
    ajuste: [],
    errores: [
      "Abrir los codos hacia fuera.",
      "Mover el hombro y convertirlo en un press.",
    ],
    senales: "Parte de atrás del brazo. Si lo notas en el codo, baja peso y acorta un poco el recorrido.",
    cuidado: null,
    sustitutos: [
      { id: "triceps-polea", motivo: "ocupada" },
      { id: "flexiones", motivo: "casa" },
    ],
    imagen: null,
    video: null,
  },
  {
    id: "encogimientos-hombros",
    nombre: "Encogimientos de hombros",
    alias: ["encogimientos", "trapecio", "shrugs"],
    grupo: "espalda",
    secundarios: ["hombro"],
    material: "mancuerna",
    patron: "aislamiento",
    nivel: "inicia",
    pasos: [
      "De pie, una mancuerna en cada mano a los lados.",
      "Sube los hombros hacia las orejas, sin doblar el codo.",
      "Aguanta arriba un segundo.",
      "Baja despacio hasta estirar.",
    ],
    ajuste: [],
    errores: [
      "Girar los hombros en círculo.",
      "Ayudarse con las rodillas.",
    ],
    senales: "Trapecio. Movimiento corto: lo que cuenta es apretar arriba, no la distancia.",
    cuidado: null,
    sustitutos: [{ id: "face-pull", motivo: "ocupada" }],
    imagen: null,
    video: null,
  },
  {
    id: "plancha-lateral",
    nombre: "Plancha lateral",
    alias: ["plancha de lado", "side plank"],
    grupo: "core",
    secundarios: ["hombro"],
    material: "peso-corporal",
    patron: "core",
    nivel: "media",
    pasos: [
      "De lado, codo debajo del hombro y pies juntos.",
      "Sube la cadera hasta hacer una línea recta.",
      "Aprieta el abdomen y el glúteo de abajo.",
      "Aguanta y cambia de lado.",
    ],
    ajuste: [],
    errores: [
      "Dejar caer la cadera.",
      "Girar el cuerpo hacia el suelo.",
    ],
    senales: "Trabaja el lateral del abdomen, que es el que sujeta la cadera al caminar. Con las rodillas apoyadas es más fácil.",
    cuidado: null,
    sustitutos: [
      { id: "plancha", motivo: "mas-facil" },
      { id: "pallof", motivo: "sin-maquina" },
    ],
    imagen: null,
    video: null,
  },
  {
    id: "bicho-muerto",
    nombre: "Bicho muerto",
    alias: ["dead bug", "bicho muerto"],
    grupo: "core",
    secundarios: [],
    material: "peso-corporal",
    patron: "core",
    nivel: "inicia",
    pasos: [
      "Boca arriba, brazos al techo y rodillas a 90º.",
      "Pega la lumbar al suelo y no la despegues en todo el ejercicio.",
      "Baja un brazo y la pierna contraria a la vez, despacio.",
      "Vuelve y cambia de lado.",
    ],
    ajuste: [],
    errores: [
      "Despegar la lumbar: ahí se acaba la serie.",
      "Ir deprisa.",
    ],
    senales: "Enseña a mantener el abdomen firme mientras se mueven brazos y piernas, que es lo que protege la espalda al levantar peso.",
    cuidado: null,
    sustitutos: [{ id: "plancha", motivo: "mas-dificil" }],
    imagen: null,
    video: null,
  },
  {
    id: "rueda-abdominal",
    nombre: "Rueda abdominal",
    alias: ["rueda", "ab wheel", "rodillo abdominal"],
    grupo: "core",
    secundarios: ["espalda"],
    material: "peso-corporal",
    patron: "core",
    nivel: "avanzada",
    pasos: [
      "De rodillas, rueda debajo de los hombros.",
      "Mete la pelvis y aprieta el abdomen.",
      "Rueda hacia delante solo hasta donde la lumbar no se arquee.",
      "Vuelve tirando con el abdomen, no con los brazos.",
    ],
    ajuste: [],
    errores: [
      "Ir más lejos de lo que aguanta la postura.",
      "Arquear la espalda al volver.",
    ],
    senales: "Si al día siguiente molesta la lumbar, fuiste demasiado lejos. El rango correcto es el que mantiene la pelvis metida.",
    cuidado: "Fuera del plan si hay molestia lumbar; para eso está el bicho muerto.",
    sustitutos: [
      { id: "plancha", motivo: "mas-facil" },
      { id: "bicho-muerto", motivo: "lumbar" },
    ],
    imagen: null,
    video: null,
  },
];
