/**
 * Tren superior y core.
 *
 * Aquí se entrena menos volumen que en pierna, pero es justo donde se cuelan
 * los desequilibrios: la espalda se queda corta porque «no es lo que ella
 * pide». El catálogo tiene suficientes tracciones y empujes para que armar un
 * día de torso completo cueste lo mismo que armar uno de pierna.
 */

import type { Ejercicio } from "../ejercicios";

export const SUPERIOR: Ejercicio[] = [
  /* ---- Espalda ---------------------------------------------------------- */
  {
    id: "jalon-al-pecho",
    nombre: "Jalón al pecho",
    alias: ["jalón", "jalon al pecho", "lat pulldown", "polea al pecho"],
    grupo: "espalda",
    secundarios: ["brazo"],
    material: "polea",
    patron: "traccion-vertical",
    nivel: "inicia",
    pasos: [
      "Siéntate con los muslos bien sujetos bajo el rodillo.",
      "Agarra la barra algo más ancho que los hombros.",
      "Saca pecho y lleva la barra a la clavícula tirando con los codos, no con las manos.",
      "Sube despacio hasta estirar del todo, sin encoger los hombros.",
    ],
    ajuste: [
      "Rodillo: apretado sobre el muslo; si te levantas al tirar, está alto.",
      "Agarre: un palmo más ancho que el hombro a cada lado.",
    ],
    errores: [
      "Echar el cuerpo muy atrás y convertirlo en un remo.",
      "Tirar con los brazos y dejar la espalda quieta.",
      "Bajar la barra por detrás de la nuca.",
    ],
    senales: "Debajo de la axila y en medio de la espalda. Si solo notas el bíceps, piensa en llevar los codos al bolsillo.",
    cuidado: null,
    sustitutos: [
      { id: "dominada-asistida", motivo: "mas-dificil" },
      { id: "remo-polea-baja", motivo: "ocupada" },
      { id: "remo-mancuerna", motivo: "sin-maquina" },
    ],
    imagen: null,
    video: null,
  },
  {
    id: "dominada-asistida",
    nombre: "Dominada asistida",
    alias: ["dominadas", "pull up", "dominada en máquina"],
    grupo: "espalda",
    secundarios: ["brazo"],
    material: "maquina",
    patron: "traccion-vertical",
    nivel: "media",
    pasos: [
      "Pon la rodilla o el pie en la plataforma de ayuda.",
      "Agarre algo más ancho que los hombros.",
      "Sube llevando el pecho a la barra, con los codos hacia abajo.",
      "Baja controlando hasta estirar.",
    ],
    ajuste: [
      "Peso de ayuda: cuanto MÁS pongas, más fácil. Empieza por la mitad de tu peso.",
    ],
    errores: [
      "Dar impulso con las piernas.",
      "Hacer medio recorrido.",
    ],
    senales: "Es el ejercicio que más cambia la espalda. Baja la ayuda cada par de semanas, aunque sea de cinco en cinco kilos.",
    cuidado: null,
    sustitutos: [
      { id: "jalon-al-pecho", motivo: "ocupada" },
    ],
    imagen: null,
    video: null,
  },
  {
    id: "remo-polea-baja",
    nombre: "Remo en polea baja",
    alias: ["remo sentado", "remo en polea", "seated row"],
    grupo: "espalda",
    secundarios: ["brazo"],
    material: "polea",
    patron: "traccion-horizontal",
    nivel: "inicia",
    pasos: [
      "Siéntate con las rodillas un poco dobladas y los pies apoyados.",
      "Espalda recta y pecho alto.",
      "Tira del agarre al ombligo llevando los codos pegados al cuerpo.",
      "Vuelve despacio sin dejar que la espalda se redondee.",
    ],
    ajuste: [
      "Agarre: estrecho para el centro de la espalda, ancho para la parte alta.",
      "Pies bien plantados en los apoyos.",
    ],
    errores: [
      "Balancearse adelante y atrás con el tronco.",
      "Encoger los hombros al tirar.",
    ],
    senales: "Centro de la espalda, entre los omóplatos. El tronco apenas se mueve.",
    cuidado: null,
    sustitutos: [
      { id: "remo-mancuerna", motivo: "ocupada" },
      { id: "jalon-al-pecho", motivo: "ocupada" },
    ],
    imagen: null,
    video: null,
  },
  {
    id: "remo-mancuerna",
    nombre: "Remo con mancuerna a una mano",
    alias: ["remo con mancuerna", "remo a una mano"],
    grupo: "espalda",
    secundarios: ["brazo", "core"],
    material: "mancuerna",
    patron: "traccion-horizontal",
    nivel: "inicia",
    pasos: [
      "Apoya rodilla y mano del mismo lado en el banco.",
      "Espalda plana como una mesa y mirada al suelo.",
      "Tira de la mancuerna hacia la cadera, codo pegado.",
      "Baja estirando del todo sin girar el tronco.",
    ],
    ajuste: [],
    errores: [
      "Girar el cuerpo para subir más.",
      "Tirar hacia el hombro en vez de hacia la cadera.",
    ],
    senales: "Un lado cada vez: notarás qué lado tira menos, y eso es información útil.",
    cuidado: null,
    sustitutos: [
      { id: "remo-polea-baja", motivo: "sin-maquina" },
      { id: "jalon-al-pecho", motivo: "ocupada" },
    ],
    imagen: null,
    video: null,
  },
  {
    id: "face-pull",
    nombre: "Face pull",
    alias: ["face pull", "jalón a la cara"],
    grupo: "espalda",
    secundarios: ["hombro"],
    material: "polea",
    patron: "traccion-horizontal",
    nivel: "inicia",
    pasos: [
      "Polea a la altura de la cara con cuerda.",
      "Agarra con las palmas mirándose y da un paso atrás.",
      "Tira llevando las manos a las orejas, separando la cuerda.",
      "Vuelve despacio.",
    ],
    ajuste: [
      "Polea a la altura de los ojos.",
      "Cuerda, no barra.",
    ],
    errores: [
      "Tirar con el tronco hacia atrás.",
      "Peso de más: aquí se va ligero y limpio.",
    ],
    senales: "Parte de atrás del hombro y entre los omóplatos. Es el mejor seguro para la postura.",
    cuidado: null,
    sustitutos: [{ id: "remo-polea-baja", motivo: "ocupada" }],
    imagen: null,
    video: null,
  },

  /* ---- Pecho ------------------------------------------------------------ */
  {
    id: "press-banca-mancuernas",
    nombre: "Press de banca con mancuernas",
    alias: ["press con mancuernas", "press banca mancuernas"],
    grupo: "pecho",
    secundarios: ["hombro", "brazo"],
    material: "mancuerna",
    patron: "empuje-horizontal",
    nivel: "inicia",
    pasos: [
      "Túmbate con las mancuernas a la altura del pecho y los codos a unos 45º.",
      "Pies bien plantados en el suelo.",
      "Empuja hacia arriba juntando ligeramente las mancuernas.",
      "Baja controlando hasta notar el estiramiento en el pecho.",
    ],
    ajuste: [],
    errores: [
      "Codos abiertos del todo, en cruz.",
      "Rebotar las mancuernas abajo.",
    ],
    senales: "Pecho, no hombro. Si el hombro se queja, cierra un poco los codos.",
    cuidado: null,
    sustitutos: [
      { id: "press-inclinado-mancuernas", motivo: "ocupada" },
      { id: "aperturas-maquina", motivo: "hombro" },
      { id: "flexiones", motivo: "casa" },
    ],
    imagen: null,
    video: null,
  },
  {
    id: "press-inclinado-mancuernas",
    nombre: "Press inclinado con mancuernas",
    alias: ["press inclinado", "incline press"],
    grupo: "pecho",
    secundarios: ["hombro", "brazo"],
    material: "mancuerna",
    patron: "empuje-horizontal",
    nivel: "inicia",
    pasos: [
      "Banco a unos 30º, ni más.",
      "Mancuernas a la altura del pecho alto, codos a 45º.",
      "Empuja arriba sin bloquear del todo.",
      "Baja controlando.",
    ],
    ajuste: ["Banco a 30º: más inclinado pasa a ser trabajo de hombro."],
    errores: [
      "Inclinar el banco demasiado.",
      "Separar la espalda del banco.",
    ],
    senales: "Parte alta del pecho, justo debajo de la clavícula.",
    cuidado: null,
    sustitutos: [
      { id: "press-banca-mancuernas", motivo: "ocupada" },
      { id: "flexiones", motivo: "casa" },
    ],
    imagen: null,
    video: null,
  },
  {
    id: "aperturas-maquina",
    nombre: "Aperturas en máquina",
    alias: ["contractora", "pec deck", "aperturas"],
    grupo: "pecho",
    secundarios: [],
    material: "maquina",
    patron: "aislamiento",
    nivel: "inicia",
    pasos: [
      "Siéntate con la espalda apoyada y los codos a la altura del pecho.",
      "Junta los brazos despacio hasta casi tocarse.",
      "Aguanta medio segundo apretando.",
      "Abre controlando hasta notar el estiramiento.",
    ],
    ajuste: [
      "Asiento: las asas a la altura del pecho, no de la cara.",
      "Apertura de inicio: la que no tire del hombro.",
    ],
    errores: [
      "Empezar desde demasiado abierto.",
      "Soltar el peso de golpe al abrir.",
    ],
    senales: "Pecho aislado, sin brazos. Es la opción amable cuando el hombro está sensible.",
    cuidado: null,
    sustitutos: [
      { id: "press-banca-mancuernas", motivo: "ocupada" },
      { id: "flexiones", motivo: "casa" },
    ],
    imagen: null,
    video: null,
  },
  {
    id: "flexiones",
    nombre: "Flexiones",
    alias: ["flexiones", "push up", "fondos en suelo"],
    grupo: "pecho",
    secundarios: ["brazo", "core"],
    material: "peso-corporal",
    patron: "empuje-horizontal",
    nivel: "inicia",
    pasos: [
      "Manos un poco más anchas que los hombros.",
      "Cuerpo recto de la cabeza al talón, abdomen firme.",
      "Baja hasta que el pecho casi toque, codos a 45º.",
      "Empuja sin que la cadera se hunda.",
    ],
    ajuste: [],
    errores: [
      "Cadera caída o culo alto.",
      "Codos totalmente abiertos.",
    ],
    senales: "Si no salen en el suelo, se hacen con las manos en un banco: es progresión, no trampa.",
    cuidado: null,
    sustitutos: [
      { id: "press-banca-mancuernas", motivo: "sin-maquina" },
      { id: "aperturas-maquina", motivo: "hombro" },
    ],
    imagen: null,
    video: null,
  },

  /* ---- Hombro ----------------------------------------------------------- */
  {
    id: "press-hombro-mancuernas",
    nombre: "Press de hombro con mancuernas",
    alias: ["press militar", "press de hombros", "shoulder press"],
    grupo: "hombro",
    secundarios: ["brazo"],
    material: "mancuerna",
    patron: "empuje-vertical",
    nivel: "media",
    pasos: [
      "Sentada con respaldo, mancuernas a la altura de las orejas.",
      "Abdomen firme para no arquear la espalda.",
      "Empuja arriba sin chocar las mancuernas.",
      "Baja controlando hasta la altura de la oreja.",
    ],
    ajuste: ["Respaldo recto, casi a 90º."],
    errores: [
      "Arquear la lumbar al empujar.",
      "Bajar demasiado y forzar el hombro.",
    ],
    senales: "Hombro entero. Si la espalda se arquea, baja el peso.",
    cuidado: "Con molestia de hombro, se cambia por elevaciones laterales hasta que pase.",
    sustitutos: [
      { id: "elevaciones-laterales", motivo: "hombro" },
      { id: "press-inclinado-mancuernas", motivo: "ocupada" },
    ],
    imagen: null,
    video: null,
  },
  {
    id: "elevaciones-laterales",
    nombre: "Elevaciones laterales",
    alias: ["elevación lateral", "laterales con mancuerna"],
    grupo: "hombro",
    secundarios: [],
    material: "mancuerna",
    patron: "aislamiento",
    nivel: "inicia",
    pasos: [
      "De pie, mancuernas a los lados y codos muy ligeramente doblados.",
      "Sube los brazos hasta la altura del hombro, ni más.",
      "Guía el movimiento con el codo, no con la mano.",
      "Baja despacio.",
    ],
    ajuste: [],
    errores: [
      "Subir por encima del hombro.",
      "Coger impulso con las piernas.",
      "Peso de más: este ejercicio es de poco peso y mucho control.",
    ],
    senales: "Quemazón justo encima del hombro. Es lo que da forma redondeada.",
    cuidado: null,
    sustitutos: [{ id: "press-hombro-mancuernas", motivo: "mas-dificil" }],
    imagen: null,
    video: null,
  },

  /* ---- Brazo ------------------------------------------------------------ */
  {
    id: "curl-biceps-mancuernas",
    nombre: "Curl de bíceps con mancuernas",
    alias: ["curl de bíceps", "curl mancuernas", "bíceps"],
    grupo: "brazo",
    secundarios: [],
    material: "mancuerna",
    patron: "aislamiento",
    nivel: "inicia",
    pasos: [
      "De pie, brazos estirados y codos pegados al cuerpo.",
      "Sube girando la muñeca hacia arriba.",
      "Aprieta arriba sin mover el codo.",
      "Baja despacio hasta estirar del todo.",
    ],
    ajuste: [],
    errores: [
      "Balancear el cuerpo.",
      "Adelantar los codos para subir más.",
    ],
    senales: "Bíceps, sin que el hombro participe.",
    cuidado: null,
    sustitutos: [{ id: "curl-martillo", motivo: "ocupada" }],
    imagen: null,
    video: null,
  },
  {
    id: "curl-martillo",
    nombre: "Curl martillo",
    alias: ["martillo", "hammer curl"],
    grupo: "brazo",
    secundarios: [],
    material: "mancuerna",
    patron: "aislamiento",
    nivel: "inicia",
    pasos: [
      "Mancuernas con las palmas mirándose, como si llevaras dos martillos.",
      "Codos pegados al cuerpo.",
      "Sube sin girar la muñeca.",
      "Baja controlando.",
    ],
    ajuste: [],
    errores: ["Mover los codos hacia delante."],
    senales: "Trabaja el lateral del brazo: es el que marca cuando se ve de frente.",
    cuidado: null,
    sustitutos: [{ id: "curl-biceps-mancuernas", motivo: "ocupada" }],
    imagen: null,
    video: null,
  },
  {
    id: "triceps-polea",
    nombre: "Extensión de tríceps en polea",
    alias: ["tríceps en polea", "jalón de tríceps", "triceps cuerda"],
    grupo: "brazo",
    secundarios: [],
    material: "polea",
    patron: "aislamiento",
    nivel: "inicia",
    pasos: [
      "Polea arriba con cuerda o barra.",
      "Codos pegados al cuerpo y tronco ligeramente inclinado.",
      "Estira los brazos abajo separando la cuerda al final.",
      "Sube despacio hasta que el codo llegue a 90º.",
    ],
    ajuste: [
      "Polea en el agujero de arriba.",
      "Cuerda si quieres más recorrido; barra si pesa más.",
    ],
    errores: [
      "Separar los codos del cuerpo.",
      "Empujar con el peso del cuerpo.",
    ],
    senales: "Parte de atrás del brazo. Los codos no se mueven del sitio.",
    cuidado: null,
    sustitutos: [{ id: "flexiones", motivo: "casa" }],
    imagen: null,
    video: null,
  },

  /* ---- Core -------------------------------------------------------------- */
  {
    id: "plancha",
    nombre: "Plancha",
    alias: ["plancha abdominal", "plank"],
    grupo: "core",
    secundarios: ["hombro"],
    material: "peso-corporal",
    patron: "core",
    nivel: "inicia",
    pasos: [
      "Antebrazos en el suelo, codos debajo de los hombros.",
      "Cuerpo recto de la cabeza al talón.",
      "Mete un poco la pelvis y aprieta glúteo y abdomen.",
      "Respira sin soltar la tensión.",
    ],
    ajuste: [],
    errores: [
      "Culo alto o cadera hundida.",
      "Aguantar más tiempo del que se puede sin perder la postura.",
    ],
    senales: "Treinta segundos buenos valen más que noventa malos. Si tiembla, está trabajando.",
    cuidado: null,
    sustitutos: [
      { id: "plancha-rodillas", motivo: "mas-facil" },
      { id: "pallof", motivo: "mas-dificil" },
    ],
    imagen: null,
    video: null,
  },
  {
    id: "plancha-rodillas",
    nombre: "Plancha con apoyo de rodillas",
    alias: ["plancha fácil", "plancha rodillas"],
    grupo: "core",
    secundarios: [],
    material: "peso-corporal",
    patron: "core",
    nivel: "inicia",
    pasos: [
      "Antebrazos en el suelo y rodillas apoyadas.",
      "Cuerpo recto de la cabeza a la rodilla.",
      "Mete la pelvis y aprieta el abdomen.",
      "Respira sin perder la línea.",
    ],
    ajuste: [],
    errores: ["Dejar la cadera caída."],
    senales: "Es el punto de partida si la plancha completa rompe la postura en diez segundos.",
    cuidado: null,
    sustitutos: [{ id: "plancha", motivo: "mas-dificil" }],
    imagen: null,
    video: null,
  },
  {
    id: "pallof",
    nombre: "Press Pallof",
    alias: ["pallof press", "antigiro en polea"],
    grupo: "core",
    secundarios: [],
    material: "polea",
    patron: "core",
    nivel: "media",
    pasos: [
      "Polea a la altura del pecho, de perfil a la torre.",
      "Agarra con las dos manos pegadas al pecho y separa los pies.",
      "Estira los brazos al frente aguantando que el cable no te gire.",
      "Vuelve al pecho sin moverte del sitio.",
    ],
    ajuste: ["Polea a la altura del esternón."],
    errores: [
      "Dejarse girar por el cable.",
      "Peso de más, que convierte el ejercicio en otra cosa.",
    ],
    senales: "El abdomen trabaja aguantando, no moviéndose. Es lo que de verdad protege la espalda.",
    cuidado: null,
    sustitutos: [{ id: "plancha", motivo: "sin-maquina" }],
    imagen: null,
    video: null,
  },
  {
    id: "crunch-abdominal",
    nombre: "Crunch abdominal",
    alias: ["abdominales", "crunch", "encogimientos"],
    grupo: "core",
    secundarios: [],
    material: "peso-corporal",
    patron: "core",
    nivel: "inicia",
    pasos: [
      "Boca arriba, rodillas dobladas y manos en el pecho o en las sienes sin tirar.",
      "Despega los omóplatos llevando las costillas a la cadera.",
      "Aguanta arriba medio segundo.",
      "Baja despacio sin apoyar la cabeza del todo.",
    ],
    ajuste: [],
    errores: [
      "Tirar del cuello con las manos.",
      "Hacer repeticiones a toda velocidad.",
    ],
    senales: "Abdomen, nunca cuello. Si notas el cuello, baja el ritmo y suelta las manos.",
    cuidado: null,
    sustitutos: [{ id: "elevacion-piernas", motivo: "mas-dificil" }],
    imagen: null,
    video: null,
  },
  {
    id: "elevacion-piernas",
    nombre: "Elevación de piernas tumbada",
    alias: ["elevación de piernas", "leg raise"],
    grupo: "core",
    secundarios: [],
    material: "peso-corporal",
    patron: "core",
    nivel: "media",
    pasos: [
      "Boca arriba, manos debajo del culo para proteger la lumbar.",
      "Piernas estiradas y juntas.",
      "Sube hasta la vertical sin despegar la lumbar del suelo.",
      "Baja despacio y para antes de tocar el suelo.",
    ],
    ajuste: [],
    errores: [
      "Arquear la lumbar al bajar: ahí hay que parar.",
      "Bajar a toda velocidad.",
    ],
    senales: "Abdomen bajo. Si la espalda se despega, acorta el recorrido o dobla las rodillas.",
    cuidado: "Si hay molestia lumbar, se hace con las rodillas dobladas.",
    sustitutos: [{ id: "crunch-abdominal", motivo: "mas-facil" }],
    imagen: null,
    video: null,
  },
];
