import { cookies } from "next/headers";
import { redirect } from "next/navigation";
import Link from "next/link";
import type { Metadata } from "next";
import Navbar from "@/components/Navbar";
import LeadRow from "@/components/LeadRow";
import { SESSION_COOKIE, verifySession, isAdmin } from "@/lib/members";
import { sbSelect } from "@/lib/supabase";
import { LEAD_STATUSES, type Lead, type LeadStatus } from "@/lib/leads";

export const metadata: Metadata = { title: "Leads / CRM", robots: { index: false, follow: false } };
export const dynamic = "force-dynamic";

export default async function LeadsPage() {
  const email = verifySession(cookies().get(SESSION_COOKIE)?.value);
  if (!email) redirect("/miembros/acceso");
  if (!isAdmin(email)) redirect("/miembros");

  let leads: Lead[] = [];
  let loadError = false;
  try {
    leads = await sbSelect<Lead>("leads", "select=*&order=created_at.desc&limit=500");
  } catch (e) {
    console.error("[leads] load", e);
    loadError = true;
  }

  const counts = new Map<LeadStatus, number>();
  for (const l of leads) {
    const s = (l.status as LeadStatus) ?? "nuevo";
    counts.set(s, (counts.get(s) ?? 0) + 1);
  }

  return (
    <>
      <Navbar />
      <main className="relative pt-16 min-h-screen">
        <div className="container-wide relative z-10 py-16">
          <div className="flex items-center justify-between gap-4 mb-8 flex-wrap">
            <div>
              <span className="section-tag">Solo administración</span>
              <h1 className="section-title">Leads / CRM</h1>
              <p className="text-sm text-ink-subtle mt-1">
                {leads.length} lead{leads.length !== 1 ? "s" : ""} · personas que rellenaron el cuestionario
              </p>
            </div>
            <Link href="/miembros/admin" className="btn-outline text-sm px-5 py-2.5">← Volver</Link>
          </div>

          {/* Resumen del pipeline */}
          {leads.length > 0 && (
            <div className="flex flex-wrap gap-2 mb-6">
              {LEAD_STATUSES.map((s) => (
                <span key={s.value} className="text-xs px-3 py-1.5 rounded-full border border-line text-ink-muted">
                  {s.label}: <strong className="text-ink">{counts.get(s.value) ?? 0}</strong>
                </span>
              ))}
            </div>
          )}

          {loadError ? (
            <div className="card-dark p-6 !transform-none">
              <p className="text-ink font-bold mb-2">Configura la tabla del CRM</p>
              <p className="text-sm text-ink-muted mb-3">
                Para activar el CRM, crea la tabla <code className="text-brand">leads</code> en Supabase
                (SQL Editor) con este comando y vuelve a entrar:
              </p>
              <pre className="text-[11px] text-ink-muted bg-page border border-line rounded-xl p-3 overflow-x-auto whitespace-pre">{`create table if not exists public.leads (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz,
  name text,
  email text unique not null,
  phone text,
  qualified boolean default false,
  answers jsonb,
  motivacion text,
  status text not null default 'nuevo',
  call_at timestamptz,
  notes text
);`}</pre>
            </div>
          ) : leads.length === 0 ? (
            <p className="text-ink-muted">Aún no hay leads. Aparecerán aquí en cuanto alguien complete el cuestionario de la landing.</p>
          ) : (
            <div className="grid gap-3 lg:grid-cols-2">
              {leads.map((lead) => (
                <LeadRow key={String(lead.id)} lead={lead} />
              ))}
            </div>
          )}
        </div>
      </main>
    </>
  );
}
